import { Student, FeeRecord } from './types';

export const mockStudents: Student[] = [
  {
    id: '1',
    name: 'Rahul Kumar',
    class: 'class1',
    fatherName: 'Ramesh Kumar',
    mobile: '9876543210',
    admissionDate: '2024-04-01',
    profileImage: '',
  },
  {
    id: '2',
    name: 'Priya Sharma',
    class: 'lkg',
    fatherName: 'Suresh Sharma',
    mobile: '9876543211',
    admissionDate: '2024-04-15',
    profileImage: '',
  },
  {
    id: '3',
    name: 'Amit Singh',
    class: 'class3',
    fatherName: 'Vijay Singh',
    mobile: '9876543212',
    admissionDate: '2023-07-10',
    profileImage: '',
  },
  {
    id: '4',
    name: 'Neha Gupta',
    class: 'ukg',
    fatherName: 'Rakesh Gupta',
    mobile: '9876543213',
    admissionDate: '2024-01-20',
    profileImage: '',
  },
  {
    id: '5',
    name: 'Arjun Yadav',
    class: 'class5',
    fatherName: 'Mahesh Yadav',
    mobile: '9876543214',
    admissionDate: '2022-04-01',
    profileImage: '',
  },
];

export const mockFeeRecords: FeeRecord[] = [
  {
    id: '1',
    studentId: '1',
    month: 'december',
    year: 2024,
    amount: 500,
    status: 'paid',
    paymentDate: '2024-12-05',
  },
  {
    id: '2',
    studentId: '1',
    month: 'november',
    year: 2024,
    amount: 500,
    status: 'paid',
    paymentDate: '2024-11-03',
  },
  {
    id: '3',
    studentId: '2',
    month: 'december',
    year: 2024,
    amount: 400,
    status: 'unpaid',
    paymentDate: null,
  },
  {
    id: '4',
    studentId: '3',
    month: 'december',
    year: 2024,
    amount: 600,
    status: 'paid',
    paymentDate: '2024-12-10',
  },
  {
    id: '5',
    studentId: '4',
    month: 'december',
    year: 2024,
    amount: 400,
    status: 'unpaid',
    paymentDate: null,
  },
  {
    id: '6',
    studentId: '5',
    month: 'december',
    year: 2024,
    amount: 700,
    status: 'paid',
    paymentDate: '2024-12-01',
  },
];
